export const RESET_ALL_REDUCERS = 'RESET_ALL_REDUCERS';
export const FETCH_MOVIES = 'FETCH_MOVIES';

export const ADD_BANNER = 'ADD_BANNER';

export const GET_FAVORITE = 'GET_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
